# Generated by Django 4.0 on 2024-09-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['order_id', 'id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order_id', 'id']},
        ),
    ]
