# Generated by Django 4.0 on 2024-09-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_district_options_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
