# Generated by Django 4.0 on 2024-09-02 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0003_direction'),
        ('common', '0005_social'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('passport', models.CharField(max_length=20)),
                ('pinfl', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('in_process', 'Jarayonda')], max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('accepted_at', models.DateField(blank=True, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.direction')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
