# Generated by Django 5.1 on 2024-09-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('in_process', 'Jarayonda')], max_length=20, null=True),
        ),
    ]
