# Generated by Django 5.1 on 2024-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('in_process', 'Jarayonda')], default='in_process', max_length=20),
        ),
    ]
