# Generated by Django 5.1 on 2024-09-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_faculty_options_alter_direction_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='education.faculty'),
        ),
    ]
